startpoint: /src
excludeDir:
    - Tests
    - DependencyInjection
    - Command
    - RhinoReportBundle
excludeFile:
    - .*Bundle\.php
    - .*Test\.php
    - .*\.phar
    - FieldFilterType.php
    - NumberFilterType.php